obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[0, 0.4], [1.3, 0.4], [1.3, -0.4], [0, -0.4]]
footprint: [[0.7, 0.375], [0.7, -0.375], [-0.7, -0.375], [-0.7, 0.375]]
#footprint: [[1, 0.7], [1, -0.7], [-1, -0.7], [-1, -0.7]]
#robot_radius: ir_of_robot
#robot_radius: 1.0 # distance a circular robot should be clear of the obstacle
inflation_radius: 5

observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan_filtered, marking: true, clearing: true}
transform_tolerance: 0.3
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
