obstacle_range: 4
raytrace_range: 4.5
#footprint: [[0, 0.4], [1.3, 0.4], [1.3, -0.4], [0, -0.4]]
footprint: [[-0.55, 0.4], [-0.55, -0.4], [0.75, -0.4], [0.75, 0.4]]
#footprint: [[1, 0.7], [1, -0.7], [-1, -0.7], [-1, -0.7]]
#robot_radius: ir_of_robot
#robot_radius: 1.0 # distance a circular robot should be clear of the obstacle


observation_sources: laser_scan_sensor #point_cloud_sensor

# marking - add obstacle information to cost map
# clearing - clear obstacle information to cost map
laser_scan_sensor: {
  sensor_frame: laser,
  data_type: LaserScan, 
  topic: /scan, 
  marking: true, clearing: true}

transform_tolerance: 0.3
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
