# static_map - True if using existing map
global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 3.0
  publish_frequency: 3.0
  resolution: 0.05
  static_map: true
  width: 15
  height: 15.0
  inflation_radius: 0.05



